[package]
name = "grokking"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
candle-core = { version = "0.5.1", features = ["cuda"] }
candle-nn = { version = "0.5.1", features = ["cuda"] }
clap = { version = "4.5.4", features = ["derive"] }
csv = "1.3.0"
rand = "0.8.5"
